language: go
sudo: false
go: 1.12.5
env:
  global:
  - PATH=$HOME/gopath/bin:$HOME/bin:$PATH
  - ARTIFACTS_CONCURRENCY=5
  - ARTIFACTS_S3_BUCKET=travis-ci-gmbh
  - ARTIFACTS_TARGET_PATHS="artifacts/$TRAVIS_BUILD_NUMBER/$TRAVIS_JOB_NUMBER:artifacts/$TRAVIS_COMMIT"
  - ARTIFACTS_PERMISSIONS=public-read
  - ARTIFACTS_CACHE_CONTROL='public, max-age=315360000'
  - ARTIFACTS_LOG_FORMAT=multiline
  - ARTIFACTS_DEBUG=1
  - GO111MODULE=on
before_install:
- go get golang.org/x/tools/cmd/cover
- go install -a -race std
script:
- make distclean all crossbuild
- if [[ $TRAVIS_SECURE_ENV_VARS == true && $TRAVIS_PULL_REQUEST == false ]] ; then ./deploy ; fi
- travis_retry ./install
